# name: SERVER-CI-common

# on:
#   push:
#     paths:
#       - "packages/server/**"
#       - ".github/workflows/**"

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [12.x, 14.x]

#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: install, lint and test
#         run: |
#           yarn workspace server install
#           yarn workspace server lint
#           yarn workspace server test
