name: CI-server-deploy

on:
  push:
    paths:
      - "packages/server/**"
      - ".github/workflows/**"
    branches:
      - dev
      - stage
      - prod

jobs:
  server-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: build
        run: |
          yarn workspace server install
          yarn workspace server build
          mkdir deploy
          cp -Rp packages/server/dist deploy/
          cp -p packages/server/server.js deploy/
          cp -Rp packages/server/migrations deploy/
          cp -p packages/server/package.json deploy/
          ls -l deploy

      - name: scp build files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "deploy/*"
          target: "/var/tmp/croton-server-deploy"
          strip_components: 1
          rm: true

      - name: ssh, move build files, run migration, restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            branch=${{ steps.extract_branch.outputs.branch }}
            echo $branch
            mkdir -p /var/www/croton/server/$branch
            rm -Rf /var/www/croton/server/$branch/build
            cp -Rp /var/tmp/croton-server-deploy/* /var/www/croton/server/$branch/
            ls -l /var/www/croton/server/$branch/
            cd /var/www/croton/server/$branch/
            npm install typeorm@`node -p -e "require('./package.json').dependencies.typeorm"`
            npm install ts-node@`node -p -e "require('./package.json').dependencies.ts-node"`
            npm run migration:run:linux
            sudo systemctl restart croton-server-$branch
