name: WEB-CI-deploy

on:
  push:
    paths:
      - "packages/web/**"
      - ".github/workflows/**"
    branches:
      - feat/43-https-ssl
      # - dev
      # - stage
      # - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set env vars
        run: |
          echo "::set-env name=branch::${GITHUB_REF#refs/heads/}"

      - name: build
        run: |
          echo $branch
          mkdir deploy
          cp -Rp packages/web/public/* deploy/
          ls -l deploy
          # yarn workspace web install
          # yarn workspace web build
          # ls -l
          # cp -Rp packages/web/build/* ./$dir/
          # ls -l ./$dir/

      - name: scp build files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "deploy"
          target: "/var/tmp/croton-web"
          rm: true

      - name: ssh, move build files, restart service
        uses: appleboy/ssh-action@master
        env:
          branch: $branch
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo $branch
            sudo rm -Rf /var/www/croton-web-$branch
            sudo mkdir /var/www/croton-web-$branch
            sudo cp -Rp /var/tmp/croton-web/* /var/www/croton-web-$branch
            sudo ls -l /var/www/croton-web-$branch
            # sudo systemctl restart croton-web-$branch
